name: 🔬 Website analysis

on:
  workflow_dispatch: ~
  schedule:
    # Every sunday at 1AM
    - cron:  '0 1 * * 0'

jobs:
  greenit:
    name: 🔬 Analyze with GreenIT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        greenit_configuration: [
            "analysis/conf/greenit/desktop.json",
            "analysis/conf/greenit/mobile.json",
        ]

    steps:
      - uses: faberNovel/heart-action@v4
        with:
          analysis_service: greenit
          config: ${{ matrix.greenit_configuration }}
          listener_services: slack
          slack_access_token: ${{ secrets.SLACK_ACCESS_TOKEN }}
        continue-on-error: true

  lighthouse:
    name: 🔬 Analyze with Google Lighthouse
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lighthouse_configuration: [
            "analysis/conf/lighthouse/desktop.json",
            "analysis/conf/lighthouse/mobile.json",
        ]

    steps:
      - uses: faberNovel/heart-action@v4
        with:
          analysis_service: lighthouse
          config: ${{ matrix.lighthouse_configuration }}
          listener_services: slack
          slack_access_token: ${{ secrets.SLACK_ACCESS_TOKEN }}
        continue-on-error: true

  observatory:
    name: 🔬 Analyze with Mozilla Observatory
    runs-on: ubuntu-latest

    steps:
      - uses: faberNovel/heart-action@v4
        with:
          analysis_service: observatory
          config: analysis/conf/observatory.json
          listener_services: slack
          slack_access_token: ${{ secrets.SLACK_ACCESS_TOKEN }}

  ssllabs-server:
    name: 🔬 Analyze with SSL Labs Server
    runs-on: ubuntu-latest

    steps:
      - uses: faberNovel/heart-action@v4
        with:
          analysis_service: ssllabs-server
          config: analysis/conf/ssllabs-server.json
          listener_services: slack
          slack_access_token: ${{ secrets.SLACK_ACCESS_TOKEN }}
