name: 🔬 Website analysis

on:
  workflow_dispatch: ~
  schedule:
    # All sunday at 1AM
    - cron:  '0 1 * * 0'

env:
  CHROME_PATH: /usr/bin/google-chrome-stable
  DAREBOOST_API_TOKEN: ${{ secrets.DAREBOOST_API_TOKEN }}
  SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}

jobs:
  analyze:
    name: Website analysis
    runs-on: ubuntu-latest

    steps:
      - name: Install Chrome
        id: install-chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
          sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
          apt-get update
          apt-get install --yes google-chrome-stable

      - uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
    
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: actions/checkout@v3

      - name: Install Heart packages for analysis
        run: |
          pnpm init
          pnpm install -D @fabernovel/heart-cli @fabernovel/heart-dareboost @fabernovel/heart-greenit @fabernovel/heart-lighthouse @fabernovel/heart-observatory @fabernovel/heart-slack @fabernovel/heart-ssllabs-server
        working-directory: ./analysis

      - name: 🔬 Analyze the website with Dareboost
        run: pnpm exec heart dareboost --file conf/dareboost.json
        working-directory: ./analysis
        continue-on-error: true

      - name: 🔬 Analyze the website with GreenIT
        run: pnpm exec heart greenit --file conf/greenit.json
        working-directory: ./analysis
        continue-on-error: true

      - name: 🔬 Analyze the website with Google Lighthouse
        run: pnpm exec heart lighthouse --file conf/lighthouse.json
        working-directory: ./analysis
        continue-on-error: true

      - name: 🔬 Analyze the website with Mozilla Observatory
        run: pnpm exec heart observatory --file conf/observatory.json
        working-directory: ./analysis
        continue-on-error: true

      - name: 🔬 Analyze the website with SSL Labs Server
        run: pnpm exec heart ssllabs-server --file conf/ssllabs-server.json
        working-directory: ./analysis
        continue-on-error: true
