name: 🔬 Website analysis

on:
  workflow_dispatch: ~
  schedule:
    # Every sunday at 1AM
    - cron:  '0 1 * * 0'

jobs:
  greenit:
    name: 🔬 Analyze with GreenIT
    runs-on: ubuntu-latest
    strategy:
      matrix:
        greenit_configuration: [
            "analysis/conf/greenit/desktop.json",
            "analysis/conf/greenit/mobile.json",
        ]

    steps:
      - uses: faberNovel/heart-action@v1.0.0
        with:
          analysis_service: greenit
          file: ${{ matrix.greenit_configuration }}
        continue-on-error: true

  greenit_fabernovbel:
    runs-on: ubuntu-latest
    steps:
      - uses: faberNovel/heart-action@v1.0.0
        with:
          analysis_service: greenit
          inline: '{"url":"https://www.fabernovel.com"}'

  greenit_lemonde:
    runs-on: ubuntu-latest
    steps:
      - uses: faberNovel/heart-action@v1.0.0
        with:
          analysis_service: greenit
          inline: '{"url":"https://www.lemonde.fr"}'

  greenit_ecoindex:
    runs-on: ubuntu-latest
    steps:
      - uses: faberNovel/heart-action@v1.0.0
        with:
          analysis_service: greenit
          inline: '{"url":"https://www.ecoindex.fr"}'

  # lighthouse:
  #   name: 🔬 Analyze with Google Lighthouse
  #   runs-on: ubuntu-latest
  #   strategy:
  #     matrix:
  #       lighthouse_configuration: [
  #           "analysis/conf/lighthouse/desktop.json",
  #           "analysis/conf/lighthouse/mobile.json",
  #       ]

  #   steps:
  #     - uses: faberNovel/heart-action@v1.0.0
  #       with:
  #         analysis_service: lighthouse
  #         file: ${{ matrix.lighthouse_configuration }}
  #         listener_services: slack
  #         slack_api_token: ${{ secrets.SLACK_API_TOKEN }}
  #       continue-on-error: true

  # observatory:
  #   name: 🔬 Analyze with Mozilla Observatory
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: faberNovel/heart-action@v1.0.0
  #       with:
  #         analysis_service: observatory
  #         file: analysis/conf/observatory.json
  #         listener_services: slack
  #         slack_api_token: ${{ secrets.SLACK_API_TOKEN }}

  # ssllabs-server:
  #   name: 🔬 Analyze with SSL Labs Server
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: faberNovel/heart-action@v1.0.0
  #       with:
  #         analysis_service: ssllabs-server
  #         file: analysis/conf/ssllabs-server.json
  #         listener_services: slack
  #         slack_api_token: ${{ secrets.SLACK_API_TOKEN }}
